# Delete current file
DEL script-message-to delete_current_file delete-file DEL "Press Delete again to confirm"
Shift+DEL script-message-to delete_current_file delete-file
CTRL+/ script-binding select/menu
CTRL+p script-binding uosc/menu-blurred
mbtn_right script-binding uosc/menu
